[terminal.shell]
program = "wsl.exe"
args = ["~"]

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold Italic" }
size = 12.0

