[terminal.shell]
program = "wsl.exe"
args = ["~"]

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold Italic" }
size = 12.0

[colors.primary]
background = "#232A2E"   # bg_dim
foreground = "#D3C6AA"   # fg

[colors.normal]
black   = "#232A2E"  # bg_dim
red     = "#E67E80"
green   = "#A7C080"
yellow  = "#DBBC7F"
blue    = "#7FBBB3"
magenta = "#D699B6"  # purple
cyan    = "#83C092"  # aqua
white   = "#D3C6AA"  # fg

[colors.bright]
black   = "#343F44"  # bg1 (a bit lighter black)
red     = "#E67E80"
green   = "#A7C080"
yellow  = "#DBBC7F"
blue    = "#7FBBB3"
magenta = "#D699B6"
cyan    = "#83C092"
white   = "#D3C6AA"

[colors.cursor]
text = "#232A2E"         # same as bg_dim
cursor = "#D3C6AA"       # fg

[colors.selection]
text = "#232A2E"
background = "#D3C6AA"

[colors.search.matches]
foreground = "#232A2E"
background = "#DBBC7F"

[colors.search.focused_match]
foreground = "#232A2E"
background = "#A7C080"

[colors.hints.start]
foreground = "#232A2E"
background = "#7FBBB3"

[colors.hints.end]
foreground = "#232A2E"
background = "#DBBC7F"

[colors.footer_bar]
background = "#343F44"
foreground = "#D3C6AA"

[window]
decorations = "full"
